# Generated by Django 3.0.6 on 2021-05-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_task_1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, unique=True, validators=[my_task_1.models.username_validator])),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=1000)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=20, validators=[my_task_1.models.title_validator])),
                ('task_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('task_pic', models.ImageField(default='', upload_to='Images/')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
