# Generated by Django 3.1 on 2021-05-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_pic',
            field=models.ImageField(default='null', upload_to='Images/'),
        ),
    ]
